#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 23 11:44:59 2020

@author: vickysharma
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset=pd.read_csv('50_Startups.csv')
y = dataset.iloc[:, 4].values
X = dataset.iloc[:, :-1].values

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder = LabelEncoder()

X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

print(y_pred)

print(y_test)
plt.plot(y_pred,y_test,color='red')
plt.title(' testing set]')
plt.xlabel('x')
plt.ylabel('y')
plt.show()
#backward elimination
import statsmodels.api as sm
X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)
x_opt=X[:,[0,3]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
print(regressor_OLS.summary())